#!/usr/bin/python3

from pprint import pprint

from flask import Flask, url_for, jsonify, request, send_from_directory, abort
app = Flask(__name__)

@app.route("/",methods=['POST'])
def echo():
    json = request.get_json()
    pprint(json)
    return jsonify([])

if __name__ == '__main__':
    app.run(debug=True,host='0.0.0.0')
