#!/usr/bin/python3

from pprint import pprint
from subprocess import Popen, PIPE
import sys

from flask import Flask, url_for, jsonify, request, send_from_directory, abort
app = Flask(__name__)

@app.route("/",methods=['POST'])
def echo():
    json = request.get_json()
    repo_name = json['repository']['name']
    repo_url = json['repository']['git_url']
    print('{} just got updated! {}'.format(repo_name,repo_url))
    cmd = "pushEGGL {} {}".format(repo_name,repo_url)
    # Pass the info to the bash script 
    try:
        p = Popen(cmd,stdout=sys.stdout, stderr=sys.stderr, shell=True)
        p.wait()
        if p.returncode != 0:
            print('Could not update the mirror for {}'.format(repo_name))
    except Exception as e:
        print('Could not update the mirror for {}: {}'.format(repo_name,e))

    return jsonify([])

if __name__ == '__main__':
    app.run(debug=False,host='0.0.0.0',port=57283)
